let TEMPLATE_KEY,INVOICE_KEY,PRICE_KEY,SERVICE_KEY,LOGO_KEY;
(function(){
const PATIENT_KEYS=['nursy_patients_v1','nursy_demo_patients_v1','NURSY_DEMO_PATIENTS','patients','PATIENTS'];
const DEFAULT_PRICE_LIST=[{service:'Grundpflege Hausbesuch',category:'Pflege',unit:'Einsatz',price:68,tax:0},{service:'Bezugspflege-Zuschlag',category:'Zuschlag',unit:'Einsatz',price:22.5,tax:0},{service:'Wundversorgung',category:'Pflege',unit:'Leistung',price:35,tax:0},{service:'Physiotherapie zuhause',category:'Physiotherapie',unit:'Einheit',price:82,tax:20},{service:'Fahrtkosten',category:'Fahrtkosten',unit:'km',price:.72,tax:20}];
const DEFAULT_SERVICES=[];
let state={patients:[],priceList:[],records:[],lines:[],selectedPatientId:'',template:{},logo:''};
async function _resolveUserId(){try{var r=await fetch('http://178.105.53.33:5000/api/me',{credentials:'include'});if(r.ok){var d=await r.json();if(d.id)return d.id;}}catch(e){}try{var r2=await fetch('http://178.105.53.33:5000/api/billing/me',{credentials:'include'});if(r2.ok){var d2=await r2.json();if(d2.ok&&d2.user&&d2.user.id)return d2.user.id;}}catch(e){}return'default';}
document.addEventListener('DOMContentLoaded',async function(){var uid=await _resolveUserId();TEMPLATE_KEY='nursy_invoice_template_v1_'+uid;INVOICE_KEY='nursy_invoices_v1_'+uid;PRICE_KEY='nursy_price_list_v1_'+uid;SERVICE_KEY='nursy_service_records_v1_'+uid;LOGO_KEY='nursy_invoice_logo_v1_'+uid;init();});
function defaultTemplate(){return{providerName:'Nursy Mobile Pflege',providerSubline:'Pflege · Physio · Betreuung zuhause',companyBlock:'Musterstraße 1\n4020 Linz\n+43 000 000000 · office@nursy.at',accent:'#3f6fe8',logoPosition:'left',paymentHint:'Bitte überweisen Sie den Betrag binnen 14 Tagen spesenfrei auf das unten angeführte Konto.',bankBlock:'IBAN AT00 0000 0000 0000 0000\nBIC NURSATWW\nKontoinhaber: Nursy Mobile Pflege',bankAlign:'left',uidNumber:'',taxNumber:'',registryNumber:'',intro:'Vielen Dank für Ihr Vertrauen. Für die im untenstehenden Zeitraum erbrachten Leistungen erlauben wir uns folgende Rechnung zu stellen.',dueDays:14};}
function loadTemplate(){return Object.assign({},defaultTemplate(),readJSON(TEMPLATE_KEY,{})||{});}
function refreshTemplate(){state.template=loadTemplate();state.logo=safeGet(LOGO_KEY);return state.template;}
function init(){state.template=loadTemplate();state.logo=safeGet(LOGO_KEY);state.priceList=sanitizePriceList(readJSON(PRICE_KEY,null)||DEFAULT_PRICE_LIST.slice());state.records=readJSON(SERVICE_KEY,null)||discoverServiceRecords();if(!state.records.length)state.records=DEFAULT_SERVICES.slice();state.patients=buildPatients();cacheEls();fillDefaults();bindEvents();renderPatients();useFirstPatientIfPossible();renderLines();renderPreview();}
function cacheEls(){state.els={invoiceNumber:byId('newInvoiceNumber'),invoiceDate:byId('newInvoiceDate'),dueDate:byId('newInvoiceDueDate'),status:byId('newInvoiceStatus'),patient:byId('newInvoicePatient'),address:byId('newInvoiceAddress'),usePatientAddress:byId('usePatientAddress'),clearAddress:byId('clearAddress'),importFromRecords:byId('importFromRecords'),addManualLine:byId('addManualLine'),saveTop:byId('saveNewInvoiceTop'),linesBody:byId('newInvoiceLinesBody'),recordHint:byId('recordHint'),previewBrand:byId('previewCreateBrand'),previewLogo:byId('previewCreateLogo'),previewProviderName:byId('previewCreateProviderName'),previewProviderSubline:byId('previewCreateProviderSubline'),previewCompanyBlock:byId('previewCreateCompanyBlock'),previewLegalBlock:byId('previewCreateLegalBlock'),previewAddress:byId('previewNewInvoiceAddress'),previewNumberInline:byId('previewNewInvoiceNumberInline'),previewDate:byId('previewNewInvoiceDate'),previewDue:byId('previewNewInvoiceDue'),previewStatus:byId('previewNewInvoiceStatus'),previewIntro:byId('previewCreateIntro'),previewLines:byId('previewNewInvoiceLines'),previewSubtotal:byId('previewNewInvoiceSubtotal'),previewTax:byId('previewNewInvoiceTax'),previewTotal:byId('previewNewInvoiceTotal'),previewPaymentHint:byId('previewCreatePaymentHint'),previewBankBlock:byId('previewCreateBankBlock'),previewFooter:byId('previewCreateFooter')};}
function fillDefaults(){if(state.els.invoiceNumber)state.els.invoiceNumber.value=createInvoiceNumber();if(state.els.invoiceDate)state.els.invoiceDate.value=isoToday();if(state.els.dueDate)state.els.dueDate.value=addDaysISO(isoToday(),Number(state.template.dueDays||14));if(state.els.status)state.els.status.value='open';}
function bindEvents(){if(state.els.patient)state.els.patient.addEventListener('change',()=>{state.selectedPatientId=state.els.patient.value||'';applyPatientAddress();renderPreview();});if(state.els.usePatientAddress)state.els.usePatientAddress.addEventListener('click',()=>{applyPatientAddress();renderPreview();});if(state.els.clearAddress)state.els.clearAddress.addEventListener('click',()=>{state.els.address.value='';renderPreview();});['address','invoiceNumber','invoiceDate','dueDate','status'].forEach(k=>{let e=state.els[k];if(e){e.addEventListener('input',renderPreview);e.addEventListener('change',renderPreview);}});if(state.els.importFromRecords)state.els.importFromRecords.addEventListener('click',importFromRecords);if(state.els.addManualLine)state.els.addManualLine.addEventListener('click',()=>{let f=state.priceList[0]||{service:'',unit:'Einheit',price:0,tax:0};state.lines.push({service:f.service||'',unit:f.unit||'Einheit',quantity:1,unitPrice:Number(f.price||0),tax:Number(f.tax||0),notes:''});renderLines();renderPreview();});if(state.els.saveTop)state.els.saveTop.addEventListener('click',saveInvoice);}
function renderPreview(){let t=refreshTemplate(),a=t.accent||'#3f6fe8',top=document.querySelector('.invoice-preview__topbar');if(top)top.style.background=a;if(state.els.previewBrand)state.els.previewBrand.className='create-brand is-'+(t.logoPosition||'left');if(state.els.previewProviderName){state.els.previewProviderName.textContent=t.providerName||defaultTemplate().providerName;state.els.previewProviderName.style.color=a;}if(state.els.previewProviderSubline)state.els.previewProviderSubline.textContent=t.providerSubline||defaultTemplate().providerSubline;if(state.els.previewCompanyBlock)state.els.previewCompanyBlock.innerHTML=nl2br(t.companyBlock||defaultTemplate().companyBlock);if(state.els.previewLegalBlock){let legal=[];if((t.uidNumber||'').trim())legal.push('UID-Nummer: '+t.uidNumber);if((t.taxNumber||'').trim())legal.push('Steuernummer: '+t.taxNumber);if((t.registryNumber||'').trim())legal.push('Gesundheitsberuferegister-Nr.: '+t.registryNumber);state.els.previewLegalBlock.innerHTML=legal.join('<br>');state.els.previewLegalBlock.style.display=legal.length?'':'none';}if(state.els.previewLogo){state.els.previewLogo.innerHTML=state.logo?'<img src="'+state.logo+'" alt="Logo" />':'Logo';}if(state.els.previewAddress)state.els.previewAddress.innerHTML=nl2br(state.els.address.value||'Bitte Patient auswählen oder Adresse eingeben.');if(state.els.previewNumberInline)state.els.previewNumberInline.textContent=state.els.invoiceNumber.value||'—';if(state.els.previewDate)state.els.previewDate.textContent=formatDate(state.els.invoiceDate.value||isoToday());if(state.els.previewDue)state.els.previewDue.textContent=formatDate(state.els.dueDate.value||addDaysISO(isoToday(),14));if(state.els.previewStatus)state.els.previewStatus.textContent=statusLabel(state.els.status.value||'open');if(state.els.previewIntro)state.els.previewIntro.textContent=t.intro||defaultTemplate().intro;if(state.els.previewPaymentHint)state.els.previewPaymentHint.textContent=t.paymentHint||defaultTemplate().paymentHint;if(state.els.previewBankBlock)state.els.previewBankBlock.innerHTML=nl2br(t.bankBlock||defaultTemplate().bankBlock);if(state.els.previewFooter)state.els.previewFooter.style.textAlign=t.bankAlign||'left';renderPreviewLines();}
function renderPreviewLines(){let b=state.els.previewLines;if(b){b.innerHTML='';if(!state.lines.length)b.innerHTML='<tr><td colspan="5"><div class="empty-state">Noch keine Positionen vorhanden.</div></td></tr>';else state.lines.forEach(l=>{let total=Number(l.quantity||0)*Number(l.unitPrice||0),tr=document.createElement('tr');tr.innerHTML='<td>'+esc(l.service||'Leistung')+(l.notes?'<div style="color:rgba(15,26,51,.60); font-size:12px; margin-top:4px;">'+esc(l.notes)+'</div>':'')+'</td><td>'+formatNumber(l.quantity||0)+'</td><td>'+esc(l.unit||'Einheit')+'</td><td class="num">'+formatCurrency(l.unitPrice||0)+'</td><td class="num">'+formatCurrency(total)+'</td>';b.appendChild(tr);});}let sub=state.lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unitPrice||0),0),tax=state.lines.reduce((s,l)=>s+(Number(l.quantity||0)*Number(l.unitPrice||0)*Number(l.tax||0)/100),0),total=sub+tax;if(state.els.previewSubtotal)state.els.previewSubtotal.textContent=formatCurrency(sub);if(state.els.previewTax)state.els.previewTax.textContent=formatCurrency(tax);if(state.els.previewTotal)state.els.previewTotal.textContent=formatCurrency(total);}
function renderPatients(){let s=state.els.patient;if(!s)return;s.innerHTML='<option value="">Bitte auswählen</option>'+state.patients.map(p=>'<option value="'+escAttr(p.id)+'">'+esc(p.name)+'</option>').join('');}
function useFirstPatientIfPossible(){if(!state.patients.length||!state.els.patient)return;state.selectedPatientId=state.patients[0].id;state.els.patient.value=state.selectedPatientId;applyPatientAddress();}
function applyPatientAddress(){let p=getSelectedPatient();if(!p||!state.els.address)return;state.els.address.value=p.address||'';}
function getSelectedPatient(){return state.patients.find(p=>String(p.id)===String(state.selectedPatientId||state.els.patient.value||''))||null;}
function importFromRecords(){let p=getSelectedPatient(),pid=String(p&&p.id?p.id:state.els.patient.value||''),pn=String(p&&p.name?p.name:'').trim().toLowerCase(),m=state.records.filter(r=>{let rid=String(r.patientId||''),rn=String(r.patientName||'').trim().toLowerCase();return(pid&&rid===pid)||(pn&&rn===pn);});if(!m.length){state.lines=[];if(state.els.recordHint)state.els.recordHint.textContent='Für diesen Patienten wurden keine Leistungen gefunden. Du kannst manuell Positionen hinzufügen.';renderLines();renderPreview();return;}state.lines=m.map(r=>{let pm=matchPriceEntry(r.service);return{service:r.service||'Leistung',unit:r.unit||(pm?pm.unit:'Einheit'),quantity:Number(r.quantity||1),unitPrice:Number(r.unitPrice!=null?r.unitPrice:(pm?pm.price:0)),tax:Number(r.taxRate!=null?r.taxRate:(pm?pm.tax:0)),notes:r.notes||''};});if(state.els.recordHint)state.els.recordHint.textContent=state.lines.length+' Leistungen aus dem Durchführungsnachweis übernommen.';renderLines();renderPreview();}
function renderLines(){let b=state.els.linesBody;if(!b)return;b.innerHTML='';if(!state.lines.length){let tr=document.createElement('tr');tr.innerHTML='<td colspan="7"><div class="empty-state">Noch keine Positionen in dieser Rechnung. Übernimm Leistungen aus der Durchführung oder füge manuell eine Position hinzu.</div></td>';b.appendChild(tr);return;}state.lines.forEach((l,i)=>{let tr=document.createElement('tr');tr.innerHTML='<td><select class="mini-select" data-index="'+i+'" data-field="service">'+serviceOptions(l.service)+'</select></td><td><input class="mini-input" data-index="'+i+'" data-field="unit" type="text" value="'+escAttr(l.unit)+'" /></td><td><input class="mini-input" data-index="'+i+'" data-field="quantity" type="number" min="0" step="0.01" value="'+Number(l.quantity||0)+'" /></td><td><input class="mini-input" data-index="'+i+'" data-field="unitPrice" type="number" min="0" step="0.01" value="'+Number(l.unitPrice||0)+'" /></td><td><input class="mini-input" data-index="'+i+'" data-field="tax" type="number" min="0" step="0.1" value="'+Number(l.tax||0)+'" /></td><td><input class="mini-input" data-index="'+i+'" data-field="notes" type="text" value="'+escAttr(l.notes||'')+'" placeholder="Notiz" /></td><td><button class="control btn" type="button" data-remove-line="'+i+'">Entfernen</button></td>';b.appendChild(tr);});b.querySelectorAll('[data-index]').forEach(e=>{e.addEventListener('input',handleLineChange);e.addEventListener('change',handleLineChange);});b.querySelectorAll('[data-remove-line]').forEach(btn=>btn.addEventListener('click',()=>{state.lines.splice(Number(btn.getAttribute('data-remove-line')),1);renderLines();renderPreview();}));}
function handleLineChange(e){let el=e.target,idx=Number(el.getAttribute('data-index')),f=el.getAttribute('data-field');if(!state.lines[idx]||!f)return;if(f==='service'){state.lines[idx].service=el.value;let m=matchPriceEntry(el.value);if(m){state.lines[idx].unit=m.unit||state.lines[idx].unit;state.lines[idx].unitPrice=Number(m.price||0);state.lines[idx].tax=Number(m.tax||0);renderLines();}}else state.lines[idx][f]=(f==='quantity'||f==='unitPrice'||f==='tax')?Number(el.value||0):el.value;renderPreview();}
function saveInvoice(){let p=getSelectedPatient(),t=refreshTemplate(),invoice={id:state.els.invoiceNumber.value||createInvoiceNumber(),patient:p?p.name:'Freier Empfänger',patientId:p?p.id:'',address:state.els.address.value||'',period:inferPeriod(),invoiceDate:state.els.invoiceDate.value||isoToday(),dueDate:state.els.dueDate.value||addDaysISO(isoToday(),14),amount:round2(state.lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unitPrice||0),0)+state.lines.reduce((s,l)=>s+(Number(l.quantity||0)*Number(l.unitPrice||0)*Number(l.tax||0)/100),0)),status:state.els.status.value||'open',template:t,logo:state.logo,lines:state.lines.map(l=>({label:l.service||'Leistung',qty:(formatNumber(l.quantity||0)+' '+(l.unit||'')).trim(),amount:round2(Number(l.quantity||0)*Number(l.unitPrice||0)),notes:l.notes||''}))};let items=loadInvoices();items.unshift(invoice);localStorage.setItem(INVOICE_KEY,JSON.stringify(items));_showSaveBanner('Rechnung gespeichert!');setTimeout(function(){window.location.href='invoices.html';},900);}
function inferPeriod(){let p=getSelectedPatient(),pid=String(p&&p.id?p.id:''),pn=String(p&&p.name?p.name:'').trim().toLowerCase(),m=state.records.filter(r=>(pid&&String(r.patientId||'')===pid)||(pn&&String(r.patientName||'').trim().toLowerCase()===pn));if(!m.length)return'Freie Positionen';let d=m.map(x=>normalizeDate(x.date||isoToday())).sort();return formatDate(d[0])+' – '+formatDate(d[d.length-1]);}
function serviceOptions(sel){return'<option value="">Bitte auswählen</option>'+state.priceList.map(i=>'<option value="'+escAttr(i.service)+'" '+(String(i.service)===String(sel||'')?'selected':'')+'>'+esc(i.service)+'</option>').join('');}
function matchPriceEntry(n){let z=normalizeText(n);return state.priceList.find(i=>normalizeText(i.service)===z)||state.priceList.find(i=>z.includes(normalizeText(i.service))||normalizeText(i.service).includes(z))||null;}
function buildPatients(){let ps=[];PATIENT_KEYS.forEach(k=>{let a=readJSON(k,[]);if(!Array.isArray(a))return;a.forEach((p,i)=>{let name=p.name||((p.firstName||'')+' '+(p.lastName||'')).trim();if(!name)return;ps.push({id:p.id||(k+'-'+i),name,address:p.address||joinAddress(p.street,p.zip,p.city)});});});state.records.forEach((r,i)=>{if(!(r.patientName||r.patientId))return;ps.push({id:r.patientId||('record-'+i),name:r.patientName||('Patient '+(i+1)),address:r.patientAddress||''});});return dedupePatients(ps);}
function dedupePatients(a){let o=[],s=new Set();a.forEach(p=>{let k=String(p.id||'').trim()+'|'+String(p.name||'').trim().toLowerCase();if(!p.name||s.has(k))return;s.add(k);o.push(p);});return o;}
function discoverServiceRecords(){let c=[];Object.keys(localStorage).forEach(k=>{if(!/(durch|nachweis|service|leistung|doku|dokumentation|invoice)/.test(k.toLowerCase()))return;flattenPossibleRecords(readJSON(k,null),c);});return normalizeRecords(c);}
function flattenPossibleRecords(v,a){if(!v)return;if(Array.isArray(v)){v.forEach(x=>flattenPossibleRecords(x,a));return;}if(typeof v!=='object')return;let h=['service','leistung','task','title','name','quantity','qty','unit','date','patientName','patientId'].some(k=>Object.prototype.hasOwnProperty.call(v,k));if(h)a.push(v);Object.keys(v).forEach(k=>{let ch=v[k];if(ch&&typeof ch==='object')flattenPossibleRecords(ch,a);});}
function normalizeRecords(r){let out=r.map((x,i)=>{let service=x.service||x.leistung||x.task||x.title||x.name||'';if(!service)return null;let pn=x.patientName||x.patient||x.clientName||x.klient||x.namePatient||'';return{id:'imp-'+(i+1),patientId:x.patientId||x.clientId||x.klientId||pn||('p-'+(i+1)),patientName:pn,patientAddress:x.patientAddress||x.address||x.patientStreet||x.anschrift||'',date:normalizeDate(x.date||x.datum||x.performedAt||x.createdAt||isoToday()),service,quantity:Number(x.quantity||x.qty||x.amount||1),unit:x.unit||x.einheit||'Einheit',notes:x.notes||x.notiz||x.description||'',unitPrice:x.unitPrice!=null?Number(x.unitPrice):undefined,taxRate:x.taxRate!=null?Number(x.taxRate):undefined};}).filter(Boolean),u=[],seen=new Set();out.forEach(i=>{let k=[i.patientId,i.date,i.service,i.quantity,i.unit].join('|');if(seen.has(k))return;seen.add(k);u.push(i);});return u;}
function sanitizePriceList(l){return(l||[]).map(i=>({service:String(i.service||''),category:String(i.category||'Pflege'),unit:String(i.unit||'Einheit'),price:Number(i.price||0),tax:Number(i.tax||0)}));}
function loadInvoices(){try{return JSON.parse(localStorage.getItem(INVOICE_KEY)||'[]')||[]}catch(e){return[]}}
function createInvoiceNumber(){let d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return'INV-'+y+m+day+'-'+String(loadInvoices().length+1).padStart(3,'0');}
function addDaysISO(iso,days){let d=new Date((iso||isoToday())+'T00:00:00');d.setDate(d.getDate()+Number(days||0));return d.toISOString().slice(0,10);}
function isoToday(){return new Date().toISOString().slice(0,10)}
function normalizeDate(v){if(!v)return isoToday();if(/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return String(v);let d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toISOString().slice(0,10);let m=String(v).match(/^(\d{2})\.(\d{2})\.(\d{4})$/);return m?m[3]+'-'+m[2]+'-'+m[1]:isoToday();}
function formatDate(v){let p=normalizeDate(v).split('-');return p[2]+'.'+p[1]+'.'+p[0]}
function formatCurrency(v){return new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(Number(v||0))}
function formatNumber(v){return new Intl.NumberFormat('de-AT',{maximumFractionDigits:2}).format(Number(v||0))}
function statusLabel(s){return s==='paid'?'Bezahlt':s==='overdue'?'Überfällig':'Offen'}
function round2(v){return Math.round(Number(v||0)*100)/100}
function nl2br(t){return esc(String(t||'')).replace(/\n/g,'<br>')}
function joinAddress(street,zip,city){return[street||'',[zip||'',city||''].filter(Boolean).join(' ').trim()].filter(Boolean).join('\n')}
function normalizeText(t){return String(t||'').trim().toLowerCase()}
function readJSON(k,f){try{let r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function safeGet(k){try{return localStorage.getItem(k)||''}catch(e){return''}}
function byId(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function escAttr(v){return esc(v)}
function _showSaveBanner(msg){let el=document.getElementById('_nursySaveBanner');if(!el){el=document.createElement('div');el.id='_nursySaveBanner';el.style.cssText='position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:#1a3a6b;color:#fff;padding:10px 22px;border-radius:12px;font-size:14px;font-weight:600;box-shadow:0 4px 20px rgba(0,0,0,.22);z-index:9999;pointer-events:none;transition:opacity .3s';document.body.appendChild(el);}el.textContent=msg;el.style.opacity='1';clearTimeout(el._t);el._t=setTimeout(function(){el.style.opacity='0';},2400);}
})();
