// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pflege-portal/AdminVerwaltung.tsx": () => import("../components/mockups/pflege-portal/AdminVerwaltung.tsx"),
  "./components/mockups/pflege-portal/Dashboard.tsx": () => import("../components/mockups/pflege-portal/Dashboard.tsx"),
  "./components/mockups/pflege-portal/Registrierung.tsx": () => import("../components/mockups/pflege-portal/Registrierung.tsx")
};
